name: SBOM generation
on:
  workflow_dispatch:
jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '8'
          cache: maven

      - name: Build Maven project
        run: mvn -B clean package -DskipTests

      - name: Install Syft
        run: curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin

      - name: Build SBOM
        run: syft dir:. -o cyclonedx-json > dvja-sbom.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: dvja-sbom.json
            
